const ACT = [
  {
    id: "1",
    image: "/assets/med/img4.jpg",
    name: "Praticing Mindfullness",
    desc: "Mindfulness is the practice of gently focusing your awareness on the present moment over and over again.",
    link: ["https://www.mindful.org/meditation/mindfulness-getting-started/","https://www.verywellmind.com/mindfulness-meditation-88369","https://www.mindful.org/mindfulness-how-to-do-it/","https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6557693/"],
    v_emd:"oYdrMpnE93s",
    Simage:" img src",
    ctg:"Meditation",
    lev:"-",
    rev:"A systematic review on 58,592 adults from nonclinical samples showed that trait mindfulness was positively associated with confidence, job satisfaction, performance and interpersonal relations, and negatively associated with burnout and work withdrawal.",
    howTO:[`Take a seat. Find a place to sit that feels calm and quiet to you.`,
`Set a time limit. If you're just beginning, it can help to choose a short time, such as 5 or 10 minutes.`,
`Notice your body.`,
`Feel your breath.`,
`Notice when your mind has wandered.`,
`Be kind to your wandering mind.`],
  },
  {
    id: "2",
    image: "/assets/med/img1.jpg",
    name: "Guided Meditation",
    desc: "Guided meditation describes a type of meditation led by a teacher, in person or via audio or video. When starting out, having an expert lead you through the basic steps of your meditation practice is recommended.",
    link: [
      "https://mindfulnessexercises.com/how-to-teach-meditation/how-to-lead-a-guided-meditation/",
      "https://www.tarabrach.com/guided-meditations/",
      "https://www.uclahealth.org/programs/uclamindful/free-guided-meditations/guided-meditations"
    ],
    v_emd:"mK-kGgypeI0",
    Simage:" img src",
    ctg:"Meditation",
    lev:"-",
    rev:"",
    howTO:[`Creating a Safe Space.`,`Set Reasonable Expectations.`,`Be Practiced and Prepared.`,`Establish Intention.`,`Use a Script if Needed.`,`Use Your Authentic Voice.`,`Balance Cueing with Silence.`,`Monitor Reactivity in Self and Others.`],
  },
  {
    id: "3",
    image: "/assets/med/img3.jpg",
    name: "pratice meditation",
    desc: `Meditation is a practice in which an individual uses a technique to train attention and awareness and detach from reflexive, "discursive thinking", achieving a mentally clear and emotionally calm and stable state,while not judging the meditation process itself.`,
    link:["",""],
    v_emd:"inpok4MKVLM",
    Simage:" img src",
    ctg:"Meditation",
    lev:"-",
    rev:"",
    howTO:[""],
  },
  {
    id: "4",
    image: "/assets/self/self3.jpg",
    name: "Playing Games",
    desc: "This stems in part from benefit number one. Aside from just simply having fun playing a game can help shift your focus away from the event causing stress. Playing games with friends or family is even better. ",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"Personal",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "5",
    image: "/assets/self/self4.jpg",
    name: "Journaling",
    desc: `By expressing thoughts and feelings in a journal, we can gain clarity, insight, and perspective on our lives, and develop a more positive and resilient mindset. `,
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"personal",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "6",
    image: "/assets/self/self1.jpg",
    name: "Time Management",
    desc: "Good time management allows students to plan their study schedules effectively, helping them meet deadlines, prepare for examinations thoroughly, and achieve better grades.",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"personal",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "7",
    image: "/assets/self/self2.jpg",
    name: "Excercise",
    desc: "Regular Excercise is one of the easiest ways to reduce your risk for chronic disease and to improve your quality of life, but most Americans do not move enough.",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"personal",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "8",
    name: "travelling",
    desc: "Travel can help improve your health, increase your knowledge, and allow you to meet new people and experience new cultures.",
    image: "/assets/social/soc1.jpg",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "9",
    name: "Spending Time",
    desc: "Good friends are good for your health. Friends can help you celebrate good times and provide support during bad times. Friends prevent isolation and loneliness and give you a chance to offer needed companionship, too.",
    image: "/assets/social/soc3.jpg",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "10",
    name: "Martial Arts",
    desc: "Through the practice of martial arts, we inherit confidence, mental strength, courage, tenacity, work ethic, humility, compassion, integrity, kindness, respect, honor, discipline, and much more",
    image: "/assets/social/soc4.jpg",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
  {
    id: "11",
    name: "Group Yoga",
    desc: "Group yoga classes ensure you enter the studio on your own and leave as part of a community. Group yoga classes also require group members to work together on poses, meditations, and chants.",
    image: "/assets/social/soc2.jpg",
    link: ["",""],
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
    rev:"",
    howTO:["",""],
  },
];

export default ACT;
