const ACT = [
  {
    id: "1",
    image: "/assets/med/img4.jpg",
    name: "Praticing Mindfullness",
    desc: "Mindfulness is the practice of gently focusing your awareness on the present moment over and over again.",
    link: "#",
    v_emd:"",
    Simage:" img src",
    ctg:"med",
    lev:"-",

  },
  {
    id: "2",
    image: "/assets/med/img1.jpg",
    name: "Guided Meditation",
    desc: "Mindfulness is the practice of gently focusing your awareness on the present moment over and over again.",
    link: "#",
    v_emd:"",
    Simage:" img src",
    ctg:"med",
    lev:"-",
  },
  {
    id: "3",
    image: "/assets/med/img3.jpg",
    name: "pratice meditation",
    desc: "Mindfulness is the practice of gently focusing your awareness on the present moment over and over again.",
    link: "#",
    v_emd:"",
    Simage:" img src",
    ctg:"med",
    lev:"-",
  },
  {
    id: "4",
    image: "/assets/self/self3.jpg",
    name: "Playing Games",
    desc: "This stems in part from benefit number one. Aside from just simply having fun playing a game can help shift your focus away from the event causing stress. Playing games with friends or family is even better. ",
    link: "#",
    v_emd:"",
    Simage:" img src",
    ctg:"Personal",
    lev:"-",
  },
  {
    id: "5",
    image: "/assets/self/self4.jpg",
    name: "Journalling",
    desc: `By expressing thoughts and feelings in a journal, we can gain clarity, insight, and perspective on our lives, and develop a more positive and resilient mindset. `,
    link: "",
    v_emd:"",
    Simage:" img src",
    ctg:"personal",
    lev:"-",
  },
  {
    id: "6",
    image: "/assets/self/self1.jpg",
    name: "Time Management",
    desc: "Good time management allows students to plan their study schedules effectively, helping them meet deadlines, prepare for examinations thoroughly, and achieve better grades.",
    link: "#",
    v_emd:"",
    Simage:" img src",
    ctg:"personal",
    lev:"-",
  },
  {
    id: "7",
    image: "/assets/self/self2.jpg",
    name: "Excercise",
    desc: "Regular Excercise is one of the easiest ways to reduce your risk for chronic disease and to improve your quality of life, but most Americans do not move enough.",
    link: "#",
    v_emd:"",
    Simage:" img src",
    ctg:"personal",
    lev:"-",
  },
  {
    id: "8",
    name: "travelling",
    desc: "Travel can help improve your health, increase your knowledge, and allow you to meet new people and experience new cultures.",
    image: "/assets/social/soc1.jpg",
    link: "/links",
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
  },
  {
    id: "9",
    name: "Spending Time",
    desc: "Good friends are good for your health. Friends can help you celebrate good times and provide support during bad times. Friends prevent isolation and loneliness and give you a chance to offer needed companionship, too.",
    image: "/assets/social/soc3.jpg",
    link: "/links",
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
  },
  {
    id: "10",
    name: "Martial Arts",
    desc: "Through the practice of martial arts, we inherit confidence, mental strength, courage, tenacity, work ethic, humility, compassion, integrity, kindness, respect, honor, discipline, and much more",
    image: "/assets/social/soc4.jpg",
    link: "/links",
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
  },
  {
    id: "11",
    name: "Group Yoga",
    desc: "Group yoga classes ensure you enter the studio on your own and leave as part of a community. Group yoga classes also require group members to work together on poses, meditations, and chants.",
    image: "/assets/social/soc2.jpg",
    link: "/links",
    v_emd:"",
    Simage:" img src",
    ctg:"social",
    lev:"-",
  },
];

export default ACT;
