const ACT2 = [
    
    {
        id: "1",
        image: "/assets/ActAssets/",
        name: "Deep Breathing Exercises",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Meditation",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "2",
        image: "/assets/ActAssets/MuscleRelaxation.jpg",
        name: "Progressive Muscle Relaxation",
        desc: "Diaphragmatic breathing, abdominal breathing, belly breathing, or deep breathing, is breathing that is done by contracting the diaphragm, a muscle located horizontally between the thoracic cavity and abdominal cavity. Air enters the lungs as the diaphragm strongly contracts, but unlike during traditional relaxed breathing (eupnea) the intercostal muscles of the chest do minimal work in this process. The belly also expands during this type of breathing to make room for the contraction of the diaphragm.",
        link: ["https://www.physio-pedia.com/Breathing_Exercises"],
        v_emd:"395ZloN4Rr8",
        Simage:"",
        ctg:"Meditation",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "3",
        image: "/assets/ActAssets/gratitude.jpg ",
        name: "Gratitude Practice",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Meditation",
        lev:"-",
        rev:"",
        howTO:[``],
      },

      //physical activities

      {
        id: "4",
        image: " ",
        name: "Yoga or Stretching",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"physical activities",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "5",
        image: "/assets/ActAssets/Jogging.jpg",
        name: "Walking or Jogging ",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"physical activities",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "6",
        image: "/assets/ActAssets/Dance.jpg",
        name: "Dance",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"physical activities",
        lev:"-",
        rev:"",
        howTO:[``],
      },

    //    Journaling & Self-Reflection

    {
        id: "7",
        image: " ",
        name: "Stream-of-Consciousness Writing ",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Journaling & Self-Reflection",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "8",
        image: "/assets/ActAssets/MoodTracking.jpg",
        name: "Mood Tracking",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Journaling & Self-Reflection",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "9",
        image: "/assets/ActAssets/futureself.jpg",
        name: "Future Self Letters",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Journaling & Self-Reflection",
        lev:"-",
        rev:"",
        howTO:[``],
      },

    //Creative Outlets
    {
        id: "10",
        image: "/assets/ActAssets/Painting.jpg",
        name: "Drawing or Painting ",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "11",
        image: "/assets/ActAssets/musicThreapy.jpg",
        name: "Music Therapy",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "12",
        image: "/assets/ActAssets/DiyCrafts.jpg",
        name: "DIY Crafts",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "13",
        image: "/assets/ActAssets/poetry.jpg",
        name: "Writing Poetry or Stories",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },

    //   Self-Care & Personal Enjoyment

    {
        id: "14",
        image: "/assets/ActAssets/RelaxingBath.jpg",
        name: "Take a Relaxing Bath",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "15",
        image: "/assets/ActAssets/skincare.jpg",
        name: "Skincare Routine",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "16",
        image: "/assets/ActAssets/Cooking.jpg",
        name: "Cook or Bake Something New",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "17",
        image: "/assets/ActAssets/soloDate.jpg",
        name: "Solo Date",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
]
export default ACT2;