const ACT2 = [
    
  {
      id: "1",
      image: "/assets/ActAssets/",
      name: "Deep Breathing Exercises",
      desc: "Deep breathing exercises involve slow, controlled inhalations and exhalations that engage the diaphragm to improve oxygen flow and relaxation. This technique helps reduce stress, lower heart rate, and promote a sense of calm by activating the body's parasympathetic nervous system. Practicing deep breathing regularly can enhance focus, improve lung capacity, and alleviate anxiety.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Meditation",
      lev:[1],
      rev:"",
      howTO:[``],
    },
    {
      id: "2",
      image: "/assets/ActAssets/MuscleRelaxation.jpg",
      name: "Progressive Muscle Relaxation",
      desc: "Diaphragmatic breathing, abdominal breathing, belly breathing, or deep breathing, is breathing that is done by contracting the diaphragm, a muscle located horizontally between the thoracic cavity and abdominal cavity. Air enters the lungs as the diaphragm strongly contracts, but unlike during traditional relaxed breathing (eupnea) the intercostal muscles of the chest do minimal work in this process. The belly also expands during this type of breathing to make room for the contraction of the diaphragm.",
      link: ["https://www.physio-pedia.com/Breathing_Exercises"],
      v_emd:"395ZloN4Rr8",
      Simage:"",
      ctg:"Meditation",
      lev:[2],
      rev:"",
      howTO:[``],
    },
    {
      id: "3",
      image: "/assets/ActAssets/gratitude.jpg ",
      name: "Gratitude Practice",
      desc: "Gratitude practice involves intentionally focusing on and appreciating the positive aspects of life, fostering a sense of contentment and well-being. Regularly acknowledging things to be grateful for can shift perspective, reduce stress, and enhance overall happiness. This practice can be done through journaling, reflection, or expressing gratitude to others.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Meditation",
      lev:[3],
      rev:"",
      howTO:[``],
    },

    //physical activities

    {
      id: "4",
      image: " ",
      name: "Yoga or Stretching",
      desc: "Yoga and stretching help release tension, improve flexibility, and promote relaxation by connecting breath with movement. Regular practice can enhance mindfulness, reduce stress, and improve overall well-being. Even a few minutes of stretching can help ease muscle stiffness and calm the mind.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"physical activities",
      lev:[2],
      rev:"",
      howTO:[``],
    },
    {
      id: "5",
      image: "/assets/ActAssets/Jogging.jpg",
      name: "Walking or Jogging ",
      desc: "Walking or jogging is a simple yet effective way to boost mood and reduce stress by increasing endorphin levels. Whether it's a brisk walk in nature or a light jog, physical movement helps clear the mind and improve overall mental and physical health.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"physical activities",
      lev:[1],
      rev:"",
      howTO:[``],
    },
    {
      id: "6",
      image: "/assets/ActAssets/Dance.jpg",
      name: "Dance",
      desc: " Dancing is a joyful way to relieve stress and express emotions through movement. Whether following structured steps or simply moving freely, dance helps release endorphins, energize the body, and uplift the spirit.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"physical activities",
      lev:[3],
      rev:"",
      howTO:[``],
    },

  //    Journaling & Self-Reflection

  {
      id: "7",
      image: " ",
      name: "Stream-of-Consciousness Writing ",
      desc: " This practice involves writing continuously without worrying about grammar or structure, allowing thoughts and emotions to flow freely. It serves as a mental detox, helping to process emotions, reduce anxiety, and gain clarity on thoughts.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Journaling & Self-Reflection",
      lev:[1,2,3],
      rev:"",
      howTO:[``],
    },
    {
      id: "8",
      image: "/assets/ActAssets/MoodTracking.jpg",
      name: "Mood Tracking",
      desc: "Mood tracking involves noting daily emotions and patterns to gain insight into mental well-being. By identifying triggers and positive influences, this practice can help manage stress, improve self-awareness, and develop healthier coping strategies. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Journaling & Self-Reflection",
      lev:[2],
      rev:"",
      howTO:[``],
    },
    {
      id: "9",
      image: "/assets/ActAssets/futureself.jpg",
      name: "Future Self Letters",
      desc: "Writing a letter to your future self can provide motivation, perspective, and encouragement. It allows you to set intentions, reflect on personal growth, and remind yourself of your goals during challenging times. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Journaling & Self-Reflection",
      lev:[2,3],
      rev:"",
      howTO:[``],
    },

  //Creative Outlets
  {
      id: "10",
      image: "/assets/ActAssets/Painting.jpg",
      name: "Drawing or Painting ",
      desc: "Engaging in creative activities like drawing or painting provides a therapeutic outlet for emotions. Art allows for self-expression, reduces stress, and promotes relaxation, even for those without artistic experience. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Creative Outlets",
      lev:[1,2,3],
      rev:"",
      howTO:[``],
    },
    {
      id: "11",
      image: "/assets/ActAssets/musicThreapy.jpg",
      name: "Music Therapy",
      desc: "Listening to or creating music can have a profound effect on mood and stress levels. Whether through calming melodies or uplifting beats, music helps process emotions, enhance relaxation, and improve focus. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Creative Outlets",
      lev:[1,2],
      rev:"",
      howTO:[``],
    },
    {
      id: "12",
      image: "/assets/ActAssets/DiyCrafts.jpg",
      name: "DIY Crafts",
      desc: "Crafting provides a sense of accomplishment and serves as a mindful activity that reduces stress. Engaging in DIY projects like knitting, scrapbooking, or making handmade gifts can boost creativity and relaxation. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Creative Outlets",
      lev:[1,2],
      rev:"",
      howTO:[``],
    },
    {
      id: "13",
      image: "/assets/ActAssets/poetry.jpg",
      name: "Writing Poetry or Stories",
      desc: " Writing poetry or stories is a powerful way to channel emotions and express thoughts creatively. It enhances self-reflection, improves emotional well-being, and serves as an artistic escape from stress.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Creative Outlets",
      lev:[2,3],
      rev:"",
      howTO:[``],
    },

  //   Self-Care & Personal Enjoyment

  {
      id: "14",
      image: "/assets/ActAssets/RelaxingBath.jpg",
      name: "Take a Relaxing Bath",
      desc: " A warm bath can help relax muscles, soothe the mind, and create a peaceful moment of self-care. Adding essential oils, bath salts, or calming music enhances the experience and promotes deep relaxation.",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:" Self-Care & Personal Enjoyment",
      lev:[1,2],
      rev:"",
      howTO:[``],
    },
    {
      id: "15",
      image: "/assets/ActAssets/skincare.jpg",
      name: "Skincare Routine",
      desc: "A skincare routine not only improves skin health but also serves as a mindful, calming ritual. Taking time for self-care through cleansing, moisturizing, and pampering the skin can reduce stress and boost self-confidence. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:" Self-Care & Personal Enjoyment",
      lev:[1,2,3],
      rev:"",
      howTO:[``],
    },
    {
      id: "16",
      image: "/assets/ActAssets/Cooking.jpg",
      name: "Cook or Bake Something New",
      desc: "Cooking or baking engages the senses and offers a rewarding way to de-stress. Experimenting with new recipes provides a creative outlet, a sense of accomplishment, and a delicious result to enjoy. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:" Self-Care & Personal Enjoyment",
      lev:[1,2,3],
      rev:"",
      howTO:[``],
    },
    {
      id: "17",
      image: "/assets/ActAssets/soloDate.jpg",
      name: "Solo Date",
      desc: "Taking yourself on a solo date fosters self-love and personal growth. Whether it’s enjoying a coffee, watching a movie, or exploring a new place, dedicating time to oneself helps recharge and build inner confidence. ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:" Self-Care & Personal Enjoyment",
      lev:[2,3],
      rev:"",
      howTO:[``],
    },
]
export default ACT2;