const ACT2 = [
    
    // meditation
    {
      id: "1",
      image: " ",
      name: "Meditiation",
      desc: " ",
      link: [""],
      v_emd:"",
      Simage:"",
      ctg:"Meditation",
      lev:"-",
      rev:"",
      howTO:[``],
    },
    {
        id: "2",
        image: " ",
        name: "Deep Breathing Exercises",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Meditation",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "3",
        image: " ",
        name: "Progressive Muscle Relaxation",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Meditation",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "4",
        image: " ",
        name: "Gratitude Practice",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Meditation",
        lev:"-",
        rev:"",
        howTO:[``],
      },

      //physical activities

      {
        id: "5",
        image: " ",
        name: "Yoga or Stretching",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"physical activities",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "6",
        image: " ",
        name: "Walking or Jogging ",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"physical activities",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "7",
        image: " ",
        name: "Dance",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"physical activities",
        lev:"-",
        rev:"",
        howTO:[``],
      },

    //    Journaling & Self-Reflection

    {
        id: "8",
        image: " ",
        name: "Stream-of-Consciousness Writing ",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Journaling & Self-Reflection",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "9",
        image: " ",
        name: "Mood Tracking",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Journaling & Self-Reflection",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "10",
        image: " ",
        name: "Future Self Letters",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Journaling & Self-Reflection",
        lev:"-",
        rev:"",
        howTO:[``],
      },

    //Creative Outlets
    {
        id: "11",
        image: " ",
        name: "Drawing or Painting ",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "12",
        image: " ",
        name: "Music Therapy",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "13",
        image: " ",
        name: "DIY Crafts",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "14",
        image: " ",
        name: "Writing Poetry or Stories",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:"Creative Outlets",
        lev:"-",
        rev:"",
        howTO:[``],
      },

    //   Self-Care & Personal Enjoyment

    {
        id: "15",
        image: " ",
        name: "Take a Relaxing Bath",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "16",
        image: " ",
        name: "Skincare Routine",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "17",
        image: " ",
        name: "Cook or Bake Something New",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
      {
        id: "18",
        image: " ",
        name: "Solo Date",
        desc: " ",
        link: [""],
        v_emd:"",
        Simage:"",
        ctg:" Self-Care & Personal Enjoyment",
        lev:"-",
        rev:"",
        howTO:[``],
      },
]
export default ACT2;